const logos={Binance:'https://assets.coingecko.com/markets/images/52/small/binance.jpg',Bybit:'https://assets.coingecko.com/markets/images/698/small/bybit_spot.png',OKX:'https://assets.coingecko.com/markets/images/96/small/WeChat_Image_20220117220452.png',KuCoin:'https://assets.coingecko.com/markets/images/61/small/kucoin.png',Coinbase:'https://assets.coingecko.com/markets/images/23/small/Coinbase_Coin_Primary.png',Gate:'https://assets.coingecko.com/markets/images/60/small/gateio.jpg',MEXC:'https://assets.coingecko.com/markets/images/409/small/WeChat_Image_20210622160936.png'};
const exchanges=['Binance','Bybit','OKX','KuCoin','Coinbase','Gate','MEXC'];
const types=['Все','Launchpool','Launchpad','Jumpstart','Spotlight','Earn','Airdrop'];
const offers=[
{ex:'KuCoin',type:'Spotlight',name:'ALT Sale',coin:'ALT',stake:'KCS / USDT',p:{50:'$5–$15',100:'$9–$30',500:'$35–$120',1000:'$70–$220'},roi:'12%–35%',score:85,url:'https://www.kucoin.com/spotlight'},
{ex:'Bybit',type:'Launchpad',name:'EXTER Sale',coin:'EXTER',stake:'USDT / MNT',p:{50:'$8–$22',100:'$15–$45',500:'$55–$180',1000:'$110–$320'},roi:'14%–45%',score:86,url:'https://www.bybit.com/en/trade/spot/launchpad'},
{ex:'Bybit',type:'Launchpool',name:'MNT Pool',coin:'MNT',stake:'MNT / USDT',p:{50:'$7–$20',100:'$15–$45',500:'$60–$210',1000:'$120–$380'},roi:'18%–45%',score:82,url:'https://www.bybit.com/en/trade/spot/launchpool'},
{ex:'Binance',type:'Launchpool',name:'Lista DAO',coin:'LISTA',stake:'BNB / FDUSD',p:{50:'$10–$24',100:'$20–$60',500:'$90–$260',1000:'$180–$520'},roi:'20%–50%',score:80,url:'https://www.binance.com/en/launchpool'},
{ex:'OKX',type:'Jumpstart',name:'ZETA Event',coin:'ZETA',stake:'OKB / USDT',p:{50:'$5–$12',100:'$10–$25',500:'$45–$130',1000:'$90–$250'},roi:'12%–28%',score:78,url:'https://www.okx.com/jumpstart'},
{ex:'Gate',type:'Launchpad',name:'Startup XYZ',coin:'XYZ',stake:'GT / USDT',p:{50:'$4–$11',100:'$8–$20',500:'$30–$90',1000:'$65–$180'},roi:'8%–22%',score:74,url:'https://www.gate.io/startup'},
{ex:'MEXC',type:'Airdrop',name:'Kickstarter ABC',coin:'ABC',stake:'MX / USDT',p:{50:'$3–$9',100:'$6–$18',500:'$25–$70',1000:'$55–$140'},roi:'6%–18%',score:70,url:'https://www.mexc.com/launchpad'},
{ex:'Coinbase',type:'Earn',name:'OP Learn',coin:'OP',stake:'Tasks',p:{50:'$2–$7',100:'$2–$10',500:'$5–$15',1000:'$8–$25'},roi:'Learn',score:66,url:'https://www.coinbase.com/learning-rewards'}];
let state={dep:'50',ex:new Set(exchanges),type:'Все',fav:new Set(JSON.parse(localStorage.favs||'[]'))};
function deepLink(o){ const web=o.url; const app={Binance:'binance://',Bybit:'bybitapp://open',OKX:'okx://main',KuCoin:'kucoin://',Coinbase:'coinbase://',Gate:'gateio://',MEXC:'mexc://'}[o.ex]; if(!app){location.href=web;return} const t=Date.now(); location.href=app; setTimeout(()=>{ if(Date.now()-t<1600) location.href=web; },900); }
function render(){ const app=document.getElementById('app'); const filtered=offers.filter(o=>state.ex.has(o.ex)&&(state.type==='Все'||o.type===state.type)).sort((a,b)=>b.score-a.score); const best=filtered[0]; app.innerHTML=`<main class="app"><header class="top"><img class="logo" src="icon.svg"><div><h1>PromoRadar AI</h1><div class="sub">Акции топ-бирж в одном месте</div></div><button class="gear" onclick="openSettings()">⚙️</button></header><section class="panel"><div class="rowHead"><div class="label">Мой депозит</div><div class="value">${state.dep} USDT⌄</div></div><div class="chips">${['50','100','500','1000'].map(d=>`<button class="chip deposit ${state.dep===d?'active':''}" onclick="setDep('${d}')">${d}<br><small>USDT</small></button>`).join('')}</div><div class="line"></div><div class="rowHead"><div class="label">Биржи</div><div class="value">${state.ex.size} из 7⌄</div></div><div class="chips">${exchanges.slice(0,4).map(e=>exChip(e)).join('')}<button class="chip more" onclick="openSettings()">+${Math.max(0,exchanges.length-4)}⌄</button></div><div class="line"></div><div class="rowHead"><div class="label">Тип акций</div><div class="value">${state.type}⌄</div></div><div class="chips">${types.slice(0,5).map(t=>`<button class="chip ${state.type===t?'active':''}" onclick="setType('${t}')">${t}</button>`).join('')}<button class="chip" onclick="openSettings()">Ещё⌄</button></div></section><div class="section"><div><h2>Лучшие акции<br>сейчас</h2><div class="sub">${filtered.length} акций · по потенциалу</div></div><button class="sort" onclick="toggleSort()">↗ По сумме⌄</button></div>${best?`<div class="best"><div><small>Лучший вариант</small><b>${best.ex} • ${best.name}</b></div><div class="profit">${best.p[state.dep]}</div></div>`:''}<section>${filtered.map(card).join('')||'<div class="empty">Нет акций по выбранным фильтрам</div>'}</section></main><div class="settings" id="settings" onclick="if(event.target.id==='settings')closeSettings()"><div class="sheet"><h3>Настройки</h3><div class="setRow"><span>Избранное</span><span>${state.fav.size}</span></div><div class="setRow"><span>Уведомления</span><span>вкл.</span></div><div class="label" style="margin-top:14px">Биржи</div><div class="chips" style="flex-wrap:wrap;margin-top:10px;overflow:visible">${exchanges.map(e=>exChip(e)).join('')}</div><div class="label" style="margin-top:14px">Типы акций</div><div class="chips" style="flex-wrap:wrap;margin-top:10px;overflow:visible">${types.map(t=>`<button class="chip ${state.type===t?'active':''}" onclick="setType('${t}')">${t}</button>`).join('')}</div><div class="hint">Кнопка «Открыть» сначала пытается открыть приложение биржи. Если приложение не установлено или deep-link не поддержан, откроется веб-страница акции.</div><button class="close" onclick="closeSettings()">Готово</button></div></div>`; }
function exChip(e){return `<button class="chip ${state.ex.has(e)?'active':''}" onclick="toggleEx('${e}')"><img class="smallLogo" src="${logos[e]}" onerror="this.style.display='none'">${e}${state.ex.has(e)?' ✓':''}</button>`}
function card(o){const fav=state.fav.has(o.name);return `<article class="card"><div class="exLogo"><img src="${logos[o.ex]}" onerror="this.parentNode.textContent='${o.ex.slice(0,2).toUpperCase()}'"></div><div><div class="meta">${o.ex} • ${o.type}</div><div class="title">${o.name}</div><span class="tag">Монета: ${o.coin}</span><div class="cols"><div><div class="k">Вложить</div><div class="v">${o.stake}</div></div><div><div class="k">Потенциал</div><div class="v green">${o.p[state.dep]}</div></div><div><div class="k">ROI</div><div class="v green">${o.roi}</div></div></div><div class="actions"><button class="star ${fav?'on':''}" onclick="fav('${o.name}')">☆</button><button class="open" onclick='deepLink(${JSON.stringify(o)})'>Открыть</button></div></div><div class="score">${o.score}<br><span>/100</span></div></article>`}
function setDep(d){state.dep=d;render()} function setType(t){state.type=t;render()} function toggleEx(e){state.ex.has(e)?state.ex.delete(e):state.ex.add(e);render()} function openSettings(){document.getElementById('settings')?.classList.add('show')} function closeSettings(){document.getElementById('settings')?.classList.remove('show')} function fav(n){state.fav.has(n)?state.fav.delete(n):state.fav.add(n);localStorage.favs=JSON.stringify([...state.fav]);render()} function toggleSort(){offers.reverse();render()} render();
