import React, {useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home, CalendarDays, Search, Briefcase, User, Star, SlidersHorizontal, Bell, ExternalLink, Zap, ShieldCheck, Clock3, WalletCards} from 'lucide-react';
import './style.css';

const exchanges=[
 {id:'binance',name:'Binance',rank:1,color:'#f3ba2f',url:'https://www.binance.com',tag:'Top #1'},
 {id:'bybit',name:'Bybit',rank:2,color:'#f7c843',url:'https://www.bybit.com',tag:'Launchpad'},
 {id:'okx',name:'OKX',rank:3,color:'#fff',url:'https://www.okx.com',tag:'Jumpstart'},
 {id:'coinbase',name:'Coinbase',rank:4,color:'#3677ff',url:'https://www.coinbase.com',tag:'Rewards'},
 {id:'kucoin',name:'KuCoin',rank:5,color:'#24d7a3',url:'https://www.kucoin.com',tag:'Spotlight'},
];
const promos=[
 {id:1,exchange:'Binance',type:'Launchpool',title:'Lista DAO',deposit:'BNB / FDUSD',min:'0.0001 BNB',profit:'$25 – $60',roi:'25% – 60%',days:3,score:95,risk:'Низкий',difficulty:'Низкая',status:'Очень выгодно',desc:'Лучший вариант, если уже есть BNB/FDUSD. Короткий срок, высокий спрос, нормальный потенциал.'},
 {id:2,exchange:'Bybit',type:'Launchpad',title:'MNT Pool',deposit:'MNT / USDT',min:'50 USDT',profit:'$15 – $45',roi:'15% – 45%',days:2,score:92,risk:'Средний',difficulty:'Средняя',status:'Лучший выбор',desc:'Подходит для небольшого депозита. Важно проверить условия блокировки и KYC.'},
 {id:3,exchange:'OKX',type:'Jumpstart',title:'ZETA Event',deposit:'OKB',min:'10 OKB',profit:'$10 – $25',roi:'10% – 25%',days:1,score:88,risk:'Средний',difficulty:'Средняя',status:'Выгодно',desc:'Хорошо, если уже держишь OKB. Без покупки OKB специально — осторожно.'},
 {id:4,exchange:'KuCoin',type:'Spotlight',title:'ALT Sale',deposit:'KCS',min:'100 KCS',profit:'$8 – $22',roi:'8% – 22%',days:4,score:85,risk:'Средний',difficulty:'Средняя',status:'Выгодно',desc:'Интересно для держателей KCS. Нужно следить за распределением и лимитами.'},
 {id:5,exchange:'Coinbase',type:'Rewards',title:'OP Learn',deposit:'Задания',min:'$0',profit:'$2 – $10',roi:'Без вложений',days:5,score:70,risk:'Низкий',difficulty:'Низкая',status:'Без риска',desc:'Маленькая сумма, но без вложений. Подходит как бонус, не как основная стратегия.'},
 {id:6,exchange:'Gate.io',type:'Startup',title:'XYZ Listing',deposit:'GT / USDT',min:'20 USDT',profit:'$5 – $18',roi:'5% – 18%',days:6,score:65,risk:'Выше среднего',difficulty:'Средняя',status:'Проверить',desc:'Добавлено как пример шестой биржи. В v2 можно включить/выключить Gate.'},
];
function Logo({name}){const ex=exchanges.find(e=>e.name===name);return <div className="logo" style={{'--c':ex?.color||'#6dff3f'}}>{name==='Binance'?'◆':name==='OKX'?'OKX':name==='Coinbase'?'C':name==='KuCoin'?'K':name==='Bybit'?'B':'G'}</div>}
function Score({v}){return <div className="score"><svg viewBox="0 0 44 44"><circle cx="22" cy="22" r="18"/><circle cx="22" cy="22" r="18" style={{strokeDasharray:`${v*1.13} 113`}}/></svg><b>{v}</b><small>/100</small></div>}
function Card({p,onClick}){return <button className="card" onClick={()=>onClick(p)}><div className="row"><div className="row gap"><Logo name={p.exchange}/><div><strong>{p.exchange}</strong><h3>{p.type}: {p.title}</h3><p>Вложить: {p.deposit}</p><em>Потенциал {p.profit}</em></div></div><Score v={p.score}/></div></button>}
function App(){const [tab,setTab]=useState('home'); const [filter,setFilter]=useState('Все'); const [deposit,setDeposit]=useState(500); const [selected,setSelected]=useState(promos[0]);
 const filtered=useMemo(()=>promos.filter(p=>filter==='Все'||p.type===filter||p.status.includes(filter)||p.exchange===filter).sort((a,b)=>b.score-a.score),[filter]);
 const best=filtered[0]||promos[0];
 return <div className="app"><header><div><h1>{tab==='home'?'Лучшие акции сейчас':tab==='calendar'?'Календарь событий':tab==='scan'?'Сканер акций':tab==='wallet'?'У меня есть':'Профиль'}</h1><p>Обновлено локально • v1 demo</p></div><div className="head-icons"><SlidersHorizontal size={20}/><Bell size={20}/></div></header>
 {tab==='home'&&<main><section className="hero"><div><span className="pill green"><Zap size={14}/> AI Profit Score</span><h2>PromoRadar AI</h2><p>Только выгодные акции на топовых криптобиржах в одном месте.</p></div><div className="radar">◎</div></section><div className="chips">{['Все','Launchpool','Launchpad','Jumpstart','Spotlight','Binance','Bybit'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><section>{filtered.map(p=><Card key={p.id} p={p} onClick={setSelected}/>)}</section><Detail p={selected}/></main>}
 {tab==='calendar'&&<main><div className="timeline">{promos.slice(0,5).map(p=><div className="event"><div className="date">{p.days}д</div><Logo name={p.exchange}/><div><b>{p.exchange}</b><p>{p.type}: {p.title}</p></div><span>осталось {p.days} дн.</span></div>)}</div></main>}
 {tab==='scan'&&<main><div className="panel"><h2>Фильтры</h2><label>Мин. ROI <b>10%</b></label><input type="range" min="0" max="100" defaultValue="10"/><label>Мин. прибыль <b>$10</b></label><input type="range" min="0" max="100" defaultValue="20"/><label>Макс. блокировка <b>30 дней</b></label><input type="range" min="1" max="60" defaultValue="30"/><button className="primary">Показать {filtered.length} акций</button></div><section>{filtered.map(p=><Card key={p.id} p={p} onClick={setSelected}/>)}</section></main>}
 {tab==='wallet'&&<main><div className="panel"><h2>Выбери депозит</h2><div className="amounts">{[50,100,500,1000].map(v=><button className={deposit===v?'active':''} onClick={()=>setDeposit(v)}>{v}<small>USDT</small></button>)}</div><div className="recommend"><span>Лучший выбор для {deposit} USDT</span><h3>{best.exchange} • {best.type}: {best.title}</h3><strong>{best.profit}</strong><p>Ожидаемый ROI: {best.roi}</p></div></div>{filtered.slice(0,4).map(p=><Card key={p.id} p={p} onClick={setSelected}/>)}</main>}
 {tab==='profile'&&<main><section className="profile"><div className="bot">🤖</div><h2>PromoRadar AI</h2><p>Pro подписка активна</p>{['Настройки уведомлений','Мои избранные','История участия','API ключи бирж','О приложении'].map(x=><div className="menu"><span>{x}</span><b>›</b></div>)}</section></main>}
 <nav>{[['home',Home,'Главная'],['calendar',CalendarDays,'Календарь'],['scan',Search,'Сканер'],['wallet',Briefcase,'Портфель'],['profile',User,'Профиль']].map(([id,Icon,t])=><button onClick={()=>setTab(id)} className={tab===id?'on':''}><Icon size={20}/><span>{t}</span></button>)}</nav></div>}
function Detail({p}){return <section className="detail"><div className="row"><div><span className="pill green"><ShieldCheck size={14}/> {p.status}</span><h2>{p.type}: {p.title}</h2><p>{p.exchange}</p></div><Score v={p.score}/></div><h4>Потенциальная прибыль</h4><div className="profit">{p.profit}</div><div className="grid"><span>ROI</span><b>{p.roi}</b><span>Вложить</span><b>{p.deposit}</b><span>Мин. вход</span><b>{p.min}</b><span>До конца</span><b>{p.days} дня</b><span>Риск</span><b>{p.risk}</b><span>Сложность</span><b>{p.difficulty}</b></div><p className="desc">{p.desc}</p><button className="primary" onClick={()=>window.open(exchanges.find(e=>e.name===p.exchange)?.url||'#','_blank')}>Перейти на {p.exchange} <ExternalLink size={16}/></button><button className="secondary"><Star size={17}/> Добавить в избранное</button></section>}
createRoot(document.getElementById('root')).render(<App/>);
